Add Debian Bullseye support
wirenboard/flash-simcom-a76xx pull request #3
Opened 2023-03-07 11:32 UTC by KraPete

2023-03-07 12:33 UTC, sikmir approved these changes

2023-03-09 05:34 UTC, sikmir approved these changes

2023-03-09 06:24 UTC, webconn requested changes

2023-03-09 06:24 UTC, webconn commented on flash_simcom.sh
> +systemctl stop ModemManager || true
А почему потом обратно не включаем? (то же про wb-gsm)

2023-03-09 06:24 UTC, webconn commented on flash_simcom.sh
> +systemctl stop wb-gsm || true
Там ниже остался код, который по-старинке включает 5V на модем через GPIO, это так и ожидалось?

2023-03-09 06:34 UTC, KraPete commented on flash_simcom.sh
> +systemctl stop ModemManager || true
https://wirenboard.com/wiki/Modem_a76xx_flashing
Там в соседнем терминале запускается утилита от SIMCOM, и после всех манипуляций предлагается перезагрузиться.

2023-03-09 06:34 UTC, KraPete commented on flash_simcom.sh
> +systemctl stop wb-gsm || true
Скрипт рабочий, ломать ничего не хочу

2023-03-09 06:37 UTC, webconn commented on flash_simcom.sh
> +systemctl stop wb-gsm || true
Ну это странно, скрипт-то действительно сделает всё, что от него хотели, но тут вопрос в том, хорошо ли он прибрал за собой

2023-03-09 06:39 UTC, webconn commented on flash_simcom.sh
> +systemctl stop ModemManager || true
Почитал. Жуть, конечно, надо будет это в порядок привести однажды. Сейчас уже ладно

2023-03-09 07:47 UTC, webconn approved these changes

2023-03-09 07:51 UTC, webconn commented
Возможно, сейчас и правда не принципиально. Но этот скрипт явно можно будет привести в порядок, чтобы не нужно было ещё и чехарду с двумя терминалами устраивать

2023-03-09 07:52 UTC, merged